#!/bin/bash
ariacore() {
    rosrun aria_utils aria load_param
    size=$(rosrun aria_utils initializer2.py get_size)
    echo "checking $(echo $size) joints"
    okay=$(rosrun aria_utils initializer2.py get_exist)
    if [ "$(echo $okay)" == "$(echo $size)" ]; then
	echo "exist ok"
    else
	echo -e "\e[1;31m$okay done with errors\e[m"
	echo "initiation failed"
	exit 0
    fi
    okay=$(rosrun aria_utils initializer2.py apply_gain)
    echo -e "\e[1;31m$okay\e[m"
    rosrun aria_utils aria initiate
    echo "initate done"
}

ariacore